version: 2
jobs:
  build:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -yy build-essential python3 git cmake
      - run:
          name: Run CircleCI build script
          command: .circleci/build.sh
  test:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - run:
            name: Install dependencies
            command: |
              apt-get update
              apt-get install -yy build-essential python3 git cmake
      - run:
          name: Run CircleCI test script
          command: .circleci/test.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test